config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/help'

  get 'sessions/new'

  get 'users/new'
  root 'static_pages#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  get 'show' => 'users#show'
  resources :users
  resources :microposts,  only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :microposts, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
    # format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }
    
    def feed
       Micropost.where("user_id = ?", id) 
    end
    
    def self.digest(string)
       cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                     BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  
  # Confirms a logged - in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    
    before_action :logged_in_user, only: [:create,  :destroy]
    before_action :correct_user,    only: :destroy
    
    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect request.referrer || root_url
        
    end
    
    private
        def micropost_params
           params.require(:micropost).permit(:content) 
        end
        
        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url if @micropost.nil?
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
   
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger]= "Invalid email/password combination."
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
  end
  end

  def help
  end
  
  def about
    
  end
  
  def contact
    
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def new
       @user = User.new 
    end
    
    def create
        @user = User.new(user_params)
    end
    
    private
    
    def user_params
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
 
 def create
  @user = User.new(user_params)
  if @user.save
    log_in @user
    flash[:success] = "Congratulations! You have successfully logged in!"
    redirect_to @user
  else
    render 'new'
  end
 end
 
 private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # log in
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
     @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def log_out
       session.delete(:user_id)
       @current_user = nil
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def current_user?(user)
        user == current_user
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def gravatar_for(user, options = { size: 50 })
       gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
       gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
       image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSpace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Blog Space", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", '#' %></li>
          <% if logged_in? %>
          <li><%= link_to "Micropost", root_path %></li>
          <li class='dropdown'>
            <a href="#" class ="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user%></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class='divider'></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<div class="container">
<%= yield %>

<footer class ='footer'>
  <small>
    This website is prepared as an example for Kevin.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id%>">
    <%= link_to gravatar_for(micropost.user, size:50),micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class= "content"><%= micropost.content %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
            <%= link_to "delete", micropost, method: :delete,
                                            data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
            <%= render 'shared/micropost_form' %>
        </section>
    </aside>
    <div class ="col-md-8">
        <h3>Micropost Feed</h3>
        <%= render 'shared/feed'%>
    </div>
    </div>
<% else %>
<div class = "center jumbotron">
    <h1>
        Welcome to Blog Space!
    </h1>
    <h2>
        This is the home page for Blog Space sample application.
    </h2>
    <%= link_to "Sign up now!", signup_url, class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/user/new.html.erb
<h1>Sign up</h1>

<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
            
            <% end %>

    </div>
    
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            
            <%= f.label :email %>
            <%= f.text_field :email %>
            
            <%= f.label :password %>
            <%= f.password_field :password %>
            
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
            
            <%= f.submit "Create my account", class: "btn btn-primary" %>
            
            <% end %>

    </div>
    
</div>

app/views/users/show.html.erb
<div class = 'row'>
    <aside class = 'col-md-4'>
        <section class = "user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
    <div class = "col-md-8">
        <% if @user.microposts.any? %>
        <h3>Microposts (<%=@user.microposts.count %>)</h3>
        <ol class="microposts">
            <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
        <% end %>
    </div>
</div>